//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.17.0
//     from Assets/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/PlayerControls.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""NoteControls"",
            ""id"": ""2a194e19-94ca-4fe8-aeb8-dd8e0bad4acb"",
            ""actions"": [
                {
                    ""name"": ""A_Note"",
                    ""type"": ""Button"",
                    ""id"": ""c26f041a-26de-4302-b03c-1bbce72145ef"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""B_Note"",
                    ""type"": ""Button"",
                    ""id"": ""aa46b09f-ef24-4c55-a317-17a369f19834"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""C_Note"",
                    ""type"": ""Button"",
                    ""id"": ""c006a317-646f-47d5-b472-9f492ca86ada"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""D_Note"",
                    ""type"": ""Button"",
                    ""id"": ""4dc93903-aff5-42ee-888a-c7a1dbb48cbb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6daea797-693c-49f9-8423-da8a08723aa2"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A_Note"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03dfd8cb-264e-43c8-b579-4aac55f91e26"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B_Note"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29470bfb-1772-4149-8433-01ede0bbaf16"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""C_Note"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""147cb820-a1ad-4a7c-9bb8-b3d8f302ef29"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_Note"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // NoteControls
        m_NoteControls = asset.FindActionMap("NoteControls", throwIfNotFound: true);
        m_NoteControls_A_Note = m_NoteControls.FindAction("A_Note", throwIfNotFound: true);
        m_NoteControls_B_Note = m_NoteControls.FindAction("B_Note", throwIfNotFound: true);
        m_NoteControls_C_Note = m_NoteControls.FindAction("C_Note", throwIfNotFound: true);
        m_NoteControls_D_Note = m_NoteControls.FindAction("D_Note", throwIfNotFound: true);
    }

    ~@PlayerControls()
    {
        UnityEngine.Debug.Assert(!m_NoteControls.enabled, "This will cause a leak and performance issues, PlayerControls.NoteControls.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // NoteControls
    private readonly InputActionMap m_NoteControls;
    private List<INoteControlsActions> m_NoteControlsActionsCallbackInterfaces = new List<INoteControlsActions>();
    private readonly InputAction m_NoteControls_A_Note;
    private readonly InputAction m_NoteControls_B_Note;
    private readonly InputAction m_NoteControls_C_Note;
    private readonly InputAction m_NoteControls_D_Note;
    /// <summary>
    /// Provides access to input actions defined in input action map "NoteControls".
    /// </summary>
    public struct NoteControlsActions
    {
        private @PlayerControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public NoteControlsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "NoteControls/A_Note".
        /// </summary>
        public InputAction @A_Note => m_Wrapper.m_NoteControls_A_Note;
        /// <summary>
        /// Provides access to the underlying input action "NoteControls/B_Note".
        /// </summary>
        public InputAction @B_Note => m_Wrapper.m_NoteControls_B_Note;
        /// <summary>
        /// Provides access to the underlying input action "NoteControls/C_Note".
        /// </summary>
        public InputAction @C_Note => m_Wrapper.m_NoteControls_C_Note;
        /// <summary>
        /// Provides access to the underlying input action "NoteControls/D_Note".
        /// </summary>
        public InputAction @D_Note => m_Wrapper.m_NoteControls_D_Note;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_NoteControls; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="NoteControlsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(NoteControlsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="NoteControlsActions" />
        public void AddCallbacks(INoteControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_NoteControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_NoteControlsActionsCallbackInterfaces.Add(instance);
            @A_Note.started += instance.OnA_Note;
            @A_Note.performed += instance.OnA_Note;
            @A_Note.canceled += instance.OnA_Note;
            @B_Note.started += instance.OnB_Note;
            @B_Note.performed += instance.OnB_Note;
            @B_Note.canceled += instance.OnB_Note;
            @C_Note.started += instance.OnC_Note;
            @C_Note.performed += instance.OnC_Note;
            @C_Note.canceled += instance.OnC_Note;
            @D_Note.started += instance.OnD_Note;
            @D_Note.performed += instance.OnD_Note;
            @D_Note.canceled += instance.OnD_Note;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="NoteControlsActions" />
        private void UnregisterCallbacks(INoteControlsActions instance)
        {
            @A_Note.started -= instance.OnA_Note;
            @A_Note.performed -= instance.OnA_Note;
            @A_Note.canceled -= instance.OnA_Note;
            @B_Note.started -= instance.OnB_Note;
            @B_Note.performed -= instance.OnB_Note;
            @B_Note.canceled -= instance.OnB_Note;
            @C_Note.started -= instance.OnC_Note;
            @C_Note.performed -= instance.OnC_Note;
            @C_Note.canceled -= instance.OnC_Note;
            @D_Note.started -= instance.OnD_Note;
            @D_Note.performed -= instance.OnD_Note;
            @D_Note.canceled -= instance.OnD_Note;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="NoteControlsActions.UnregisterCallbacks(INoteControlsActions)" />.
        /// </summary>
        /// <seealso cref="NoteControlsActions.UnregisterCallbacks(INoteControlsActions)" />
        public void RemoveCallbacks(INoteControlsActions instance)
        {
            if (m_Wrapper.m_NoteControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="NoteControlsActions.AddCallbacks(INoteControlsActions)" />
        /// <seealso cref="NoteControlsActions.RemoveCallbacks(INoteControlsActions)" />
        /// <seealso cref="NoteControlsActions.UnregisterCallbacks(INoteControlsActions)" />
        public void SetCallbacks(INoteControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_NoteControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_NoteControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="NoteControlsActions" /> instance referencing this action map.
    /// </summary>
    public NoteControlsActions @NoteControls => new NoteControlsActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "NoteControls" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="NoteControlsActions.AddCallbacks(INoteControlsActions)" />
    /// <seealso cref="NoteControlsActions.RemoveCallbacks(INoteControlsActions)" />
    public interface INoteControlsActions
    {
        /// <summary>
        /// Method invoked when associated input action "A_Note" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnA_Note(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "B_Note" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnB_Note(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "C_Note" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnC_Note(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "D_Note" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnD_Note(InputAction.CallbackContext context);
    }
}
